### ISSUE TITLE
Type stability and reduce memory for Batch Norm

### ISSUE THREAD

**Issue by jgranek** [XtractOpen/Meganet.jl#2]
https://github.com/XtractOpen/Meganet.jl/blob/252ceef7b0b4301c779c745ae58c624dc53b83d3/src/layers/normLayer.jl#L30-L49

**Comment by lruthotto** [comment]
is this still a problem in the current version?

**Comment by jgranek** [comment]
I think this was more done as an example while we played with setting up git (issues, protected branches etc), but I also think there's still some allocation improvements that can be done instead of redefining `Y` all the time (@klensink @DavidBegert correct me if I'm wrong).

**Comment by DavidBegert** [comment]
Yes there are definitely some optimisations.

**Comment by klensink** [comment]
#48
