### ISSUE TITLE
Make tests work again

### ISSUE THREAD

**Issue by lruthotto** [XtractOpen/Meganet.jl#8]
I started in branch `fixTests` and got many things working again. I think its only the `integrators` that are missing. Please feel free to continue in that branch.

**Comment by eldadHaber** [comment]
Working on the softmax lecture. I’m not sure we have the right thing implemented …

From: Lars Ruthotto
Sent: Sunday, January 21, 2018 6:33 PM
To: XtractOpen/Meganet.jl
Cc: Subscribed
Subject: [XtractOpen/Meganet.jl] Make tests work again (#8)

I started in branch fixTests and got many things working again. I think its only the integrators that are missing. Please feel free to continue in that branch.

**Comment by klensink** [comment]
#9 Makes all tests pass
